= General Notes

:FD216: link:https://www.faraday-tech.com/download/techDocument/FD216_PB_v1.5.pdf
:imgtech: link:https://www.mips.com/press/mediatek-selects-mips-for-lte-modems/
:adi-acquisition: link:https://www.eetimes.com/mediatek-buys-adis-cellular-chip-operations/
:acquisition: link:https://www.eetimes.com/mediatek-buys-baseband-dsp-ip-licensor-coresonic/
:mt6290: link:https://www.mediatek.com/news-events/press-releases/mediatek-announces-the-availability-of-multimode-lte-modem-chipset
:low-IF: link:https://en.wikipedia.org/wiki/Low_IF_receiver
:direct-conversion: link:https://en.wikipedia.org/wiki/Direct-conversion_receiver
:cellular-frequencies: link:https://en.wikipedia.org/wiki/Cellular_frequencies

== System Overview

The SoC/LTE Modem system consists of three main parts:

. The Application Processor (<<AP>>), which is some ARM Cortex-A variant.
. The Baseband Processor (<<BP>>/BB), which is a Cortex-R4.
. The Baseband DSP (<<DSP>>), which is some Coresonic DSP.

This is actually a simplification, because there's a second, non-Coresonic DSP
to handle 2G/3G signal processing (a {FD216}[Faraday Technology FD216]),
but I'm not interested in that. Also, it seems the BP won't be a Cortex-R4 in
future devices, as {imgtech}[MediaTek has signed an agreement with
Imagination Technologies] to license some MIPS CPU core for the LTE BP in the
upcoming Helio X30 (MT6799) and later SoCs, but that doesn't matter now
because the cheaper SoCs aren't using them yet.

From what I've been able to glean from kernel sources and disassembled
binaries, the AP and the BP share some memory for loading the BP fimware, DMA,
and IPC (through virtual serial ports). They also appear to share access to
certain peripherals, like the UART and UICC interfaces. The BP has either some
or all of the DSP's memory space mapped, and I think the AP may be able to
access that directly (for, e.g., DSP memory dumps), but I'm not entirely sure.

== IC Names and Functions

* Cellular RF Frontends (RFICs)
** MT6169
* Connectivity RF Frontends (RFICs)
** MT6625
** MT6631
* Antenna Switches
** Any Skyworks SKY77xxx-xx IC
* Power Management ICs (PMICs)
** MT6328
** MT6351

=== Details

The cellular RF frontends have two main functions:

* Convert between the {low-IF}[low-IF]/{direct-conversion}[zero-IF]
  signals the SoC transmits/receives and the much higher-frequency
  {cellular-frequencies}[cellular RF signals].
* Filter and amplify the transmitted and received cellular signals.

It's important to know that the cellular RF frontends only perform these
tuning, filtering, and amplification functions, plus a few smaller
functions--they don't do any ADC/DAC, so the signals shared between the SoC
and them are entirely analog.

The connectivity RF frontends are similar to the cellular RF frontends, but
handle WiFi, Bluetooth, and GNSS instead. Like with the cellular RFICs, the
amplified, filtered, and shifted RF signals for these functions are sent into
the SoC for further processing. In addition to that, the connectivity RFICs
also include a full FM radio receiver which contains a demodulator DSP.

The antenna switches take the large number of TX/RX signals from the cellular
RF frontend and multiplex them over a smaller number of antennas. This way a
phone only needs 1-3 cellular antennas instead of 10+ antennas.

The power management ICs are sort of "kitchen sink" ICs--in addition to
performing typical power management functions like DC-DC conversion, battery
charging, and battery monitoring and management ("fuel gauge"), they perform a
number of additional funcions:

* Vibration motor driver.
* LED drivers.
* Audio CODEC (ADC/DAC).
* AUXADC for accessory detection/temperature sensing.
* Real-time clock.
* Extra GPIO.

To summarize, the PMIC handles most of the higher-power analog functionality
that isn't already handled by the RFICs or the SoC itself.

== Glossary

MediaTek uses a lot of acronyms in their code and documentation but rarely
expands them, so this glossary is my attempt at fixing that. Please note that
some of these entries are complete guesses.

[[AICE]]AICE:: Andes ICE. This is a JTAG adapter/"In-Circuit Emulator" made by
Andes Technology.

[[AP]]AP:: Applications Processor. The CPU cores that Android/Linux run on.

[[BP]]BP:: Baseband Processor. The cellular modem.

[[BROM]]BROM:: Boot ROM. The mask ROM baked into the silicon of the SoC that
holds the first code executed by the CPU. As it is a ROM, it is completely
immutable.

[[C2CRF]]C2CRF:: "Coresonic to Cortex-R(4)F"? "Core to Core RF"? Related to
access between the CR4 and the Coresonic core, meant for debugging.

[[CCCI]]CCCI:: Cross Core Communication Interface. This is the memory/DMA
interface through which the <<AP>> and the <<BP>> communicate.

[[CONN]]CONN:: "Connectivity", usually refers to the connectivity subsystem.
The connectivity subsystem includes the WiFi CPU core and possibly the
Bluetooth CPU as well.

[[CQDMA]]CQDMA:: Command-Queue DMA. This is what MediaTek calls their DMA
controller.

[[DA]]DA:: Download Agent. In the official MediaTek USB-based eMMC flashing
flow, the DA is code loaded over USB by the preloader (which itself may be
loaded over USB in BROM USB Download Mode) that interacts with the host
software to read from/write to eMMC.

[[DAA]]DAA:: "Download Agent Authentication"? When this is enabled, the
<<BROM>> will authenticate the <<DA>> before executing it.

[[DBF]]DBF:: DSP Binary Filter. As the name implies, this is binary filter
data that is loaded into and parsed by the firmware running on the Coresonic
DSP.

[[DCM]]DCM:: Dynamic Clock Management.

[[DEM]]DEM:: Debug Exchange Module/Data Exchange Module. This is a hardware
block with registers that control reset, clocking, and I/O selection for the
debug subsystem. For example, the JTAG enable/disable registers are part of
this module.

[[DSP]]DSP:: Digital Signal Processor.

[[GCE]]GCE:: Global Command Engine. A SoC peripheral that can be used to
program registers with strict timing requirements.

[[GCPU]]GCPU:: General Copy Protection Unit. A SoC peripheral used for
decrypting encrypted media. It's a microcontroller core (MD32?) with some ROM,
SRAM, and hardware accelerators for AES, SHA, MD5, RC4, DES, CRC32, DMA, etc.

[[GCU]]GCU:: GPRS Cipher Unit. An accelerator for cryptographic ciphers used
in some GSM protocols.

[[HACC]]HACC:: Something to do with Anti-Clone or secure boot? Can do AES
encryption/decryption. I think these regs are a subset of <<SEJ>>, or maybe
"HACC" is another term for "SEJ".

[[HIF]]HIF:: Host Interface. This is the interface between the SoC and the
Connectivity (WLAN/BT/GPS) core. The HIF is an abstraction layer over the
physical interface (AHB/eHPI/PCIe/SDIO/USB).

[[INFRACFG]]INFRACFG:: "Infrastructure system configuration". Refers to the
block of registers that control reset, clocking, and some miscellaneous
control signals.

[[M4U]]M4U:: Multimedia Memory Management Unit. This is what MediaTek calls
their IOMMU.

[[MCU]]MCU:: Used to refer to different processor subsystems. e.g., "APMCU"
refers to the main <<AP>> core cluster, while "MDMCU" refers to the <<BP>>
CPU. "MCUSYS" seems to refer to the <<AP>> MCU system.

[[MFG]]MFG:: MFlexGraphics. Refers to the 3D GPU subsystem.

[[MSDC]]MSDC:: Used to refer to their EMMC/SD card controller core. Possibly
"MediaTek SD Controller".

[[RXDFE]]RXDFE:: "RX Digital Front End"?

[[SBC]]SBC:: "Secure Boot Code"? Refers to secure boot functionality. When
this is enabled, the BROM will only load and run properly signed boot code.

[[SEJ]]SEJ:: Security Engine with JTAG control. Has some regs to control JTAG
enable/disable. Also has some encryption/decryption functionality (maybe
encrypted JTAG?). See also: <<HACC>>.

[[SIB]]SIB:: System Interface Box. A custom SWD/JTAG adapter used by MediaTek?
Or a hardware component inside the SoC's debug subsystem?

[[SLA]]SLA:: "Software Loader Authentication"? Some challenge-response auth to
authenticate the program loading the DA? Challenge-response auth to
authenticate the program communicating with the BROM? When this is enabled, it
disables Download Agent (DA) functionality in the BROM.

[[SST]]SST:: System Stability Tracker. This is the name of the system trace
functionality included in the <<BP>> firmware.

[[SWLA]]SWLA:: Software LA (Logic Analyzer?). It seems to be some kind of
debug functionality in the <<BP>> firmware.

[[TRNG]]TRNG:: Truly Random Number Generator.

[[WMT]]WMT:: Wireless Management Task. Refers to the WiFi/Bluetooth
drivers/API.

== History

* 2007: {adi-acquisition}[MediaTek acquires Analog Devices' cellular chip
  operations].
* 2012: {acquisition}[MediaTek acquires Coresonic], a DSP IP core company.
* 2014: {mt6290}[MediaTek releases their first LTE modem], the MT6290.

== Prior Work

* https://comsecuris.com/blog/posts/path_of_least_resistance/[Path of Least Resistance: Cellular Baseband to Application Processor Escalation on Mediatek Devices]
** More of an analysis of the kernel and userspace side of things and
   not so much about the modem firmware, but still very good and helpful.
** https://github.com/Comsecuris/mtk-baseband-sanctuary[MTK Baseband Code Elevation Research Repo]
*** https://github.com/Comsecuris/mtk-baseband-sanctuary/blob/master/ccci_md_dump/decrypt/decrypt.c[BP image decryptor]
*** https://github.com/Comsecuris/mtk-baseband-sanctuary/blob/master/ida_load_syms/loadsyms.py[Debug symbol loader]

* "Reverse engineering MT8173 PCM firmwares and ISA for a fully free
  bootchain"
** https://www.youtube.com/watch?v=9rKxfo7Gkqo[Video],
   https://web.archive.org/web/20171030164527/https://ecc2017.coreboot.org/uploads/talk/presentation/30/reverse-engineering-mt8173-pcm-firmwares-isa-fully-free-boot-chain.pdf[Slides]
** Good talk on reverse engineering the ISA of a custom MediaTek
   microcontroller core.

* https://recon.cx/2016/recordings/recon2016-02-david-carne-Black-box-reverse-engineering-for-unknown-custom-instruction-sets.mp4[Black box reverse engineering for unknown/custom instruction sets]
** "Reversing the ADF7242"
** Good talk on how to reverse engineer ISAs in general.

* https://www.robertxiao.ca/hacking/dsctf-2019-cpu-adventure-unknown-cpu-reversing/[reverse-engineering a custom, unknown CPU from a single program]
** Explains how, for a CTF competition, a custom ISA was reverse-engineered
   with only access to the executed binary and a running, remote instance of
   the code.
** By interacting with the code, they could observe how the code behaved and
   map its functionality, which enabled them to search for those patterns of
   functionality in the binary.

* https://docs.google.com/presentation/d/13OJNOb2IMwp79SDrbxSLF3i7StTgWLdD7QlYpic39r8/edit[Reversing a Japanese Wireless SD Card - From Zero to Code Execution]
** This talk includes some ISA identification techniques.
** Has links to some interesting tools:
*** https://github.com/sgayou/rbasefind[rbasefind]: A firmware base address
    search tool.
*** https://github.com/cea-sec/miasm[Miasm]: Reverse engineering framework in
    Python.
*** https://github.com/cea-sec/Sibyl[Sibyl]: A Miasm2 based function
    divination.
*** https://github.com/guedou/r2m2[r2m2]: Use miasm2 as a radare2 plugin.

* https://recon.cx/2018/brussels/resources/slides/RECON-BRX-2018-DIY-ARM-Debugger-for-Wi-Fi-Chips.pdf[DIY ARM Debugger for Wi-Fi Chips: Using Nexmon to Perform Single-Step Debugging and More on Proprietary Wi-Fi Chips]
** Explains how "Monitor debug-mode" works on ARM.
** Monitor debug-mode can be used to debug code on targets without
   accessible/enabled JTAG/SWD pins.
*** This should be useful for debugging code running on the BP's Cortex-R4
    core.

* https://web.archive.org/web/20190808113206/https://embedi.org/blog/remotely-compromise-devices-by-using-bugs-in-marvell-avastar-wi-fi-from-zero-knowledge-to-zero-click-rce/[Remotely compromise devices by using bugs in Marvell Avastar Wi-Fi: from zero knowledge to zero-click RCE]
** Marvell Avastar WiFi firmware reverse engineering.
** Blog post based on
   https://2018.zeronights.ru/en/reports/researching-marvell-avastar-wi-fi-from-zero-knowledge-to-over-the-air-zero-touch-rce/[an earlier talk]
*** https://www.youtube.com/watch?v=Him_Lf5ZJ38[Video],
    https://2018.zeronights.ru/wp-content/uploads/materials/19-Researching-Marvell-Avastar-Wi-Fi.pdf[Slides]
** Includes tips on fuzzing the firmware.
*** Uses https://github.com/Battelle/afl-unicorn[afl-unicorn] for fuzzing
    functions in the Unicorn CPU emulator.

* https://www.blackhat.com/us-19/briefings/schedule/index.html#exploiting-qualcomm-wlan-and-modem-over-the-air-15481[Exploiting Qualcomm WLAN and Modem Over-the-Air]
** https://www.youtube.com/watch?v=7lrm5tRJYSg[Video],
   https://i.blackhat.com/USA-19/Thursday/us-19-Pi-Exploiting-Qualcomm-WLAN-And-Modem-Over-The-Air.pdf[Slides],
   https://i.blackhat.com/USA-19/Thursday/us-19-Pi-Exploiting-Qualcomm-WLAN-And-Modem-Over-The-Air-wp.pdf[White Paper]
** https://www.defcon.org/html/defcon-27/dc-27-speakers.html#Gong[DEF CON 27 talk]
*** https://media.defcon.org/DEF%20CON%2027/DEF%20CON%2027%20video%20and%20slides/DEF%20CON%2027%20Conference%20-%20Xiling%20Gong%20-%20Exploiting%20Qualcomm%20WLAN%20and%20Modem%20Over%20The%20Air.mp4[Video]
    (https://media.defcon.org/DEF%20CON%2027/DEF%20CON%2027%20video%20and%20slides/DEF%20CON%2027%20Conference%20-%20Xiling%20Gong%20-%20Exploiting%20Qualcomm%20WLAN%20and%20Modem%20Over%20The%20Air.srt[Subtitles]),
    https://www.youtube.com/watch?v=KxdfX9NxfA4[Video (YouTube)],
    https://media.defcon.org/DEF%20CON%2027/DEF%20CON%2027%20presentations/DEFCON-27-Xiling-Gong-Peter-Pi-Exploiting-Qualcomm-WLAN-and-Modem-Over-The-Air.pdf[Slides]

* https://www.sstic.org/media/SSTIC2016/SSTIC-actes/how_to_not_break_lte_crypto/SSTIC2016-Article-how_to_not_break_lte_crypto-michau_devine.pdf[How to not break LTE crypto]
** MediaTek-specific modem information is in section 3.3.
* http://baseband-devel.722152.n3.nabble.com/Fun-with-the-MTK-6573-Baseband-Patching-Replacing-td4026683.html[Fun with the MTK 6573 Baseband (Patching / Replacing)]
** https://lists.osmocom.org/pipermail/baseband-devel/2017-April/005188.html[Fun with the MTK 6573 Baseband (Patching / Replacing), continued]
** Not much new information here, but still somewhat interesting.

* Mali and Mali-T GPU ISA reverse engineering talks.
** The design of the Coresonic core seems a lot like a GPU, so some of the techniques discussed here may apply.
** https://archive.fosdem.org/2014/schedule/event/lima_shader/[FOSDEM 2014: lima driver: Opening up the Mali instruction set]
*** https://video.fosdem.org/2014/H1301_Cornil/Sunday/lima_driver_Opening_up_the_Mali_instruction_set.webm[Video],
    https://archive.fosdem.org/2014/schedule/event/lima_shader/attachments/slides/439/export/events/attachments/lima_shader/slides/439/fosdem_2014_presentation.pptx[Slides]
** https://www.x.org/wiki/Events/XDC2018/Talks/#lyude_alyssa[XDC 2018: Lyude Paul & Alyssa Rosenzweig - Introducing Panfrost]
*** https://www.youtube.com/watch?v=qtt2Y7XZS3k[Video],
    https://xdc2018.x.org/slides/Panfrost-XDC_2018.pdf[Slides]
